# Generated by Django 4.2.18 on 2025-02-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_applicant_employer_remove_employerprofile_employer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='title',
        ),
        migrations.AddField(
            model_name='employer',
            name='site_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='address1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='address2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employer',
            name='address1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
