# Generated by Django 4.2.18 on 2025-02-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_employer_title_employer_site_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='applicant',
            new_name='user',
        ),
    ]
